apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: test-mvp-component-lyne
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/susdas_quay_org/mvp-dev-aumu-tenant/mvp-test-app/test-mvp-component-lyne@sha256:e552a6c58318754b94f7411ac72ffcb20b0db230881175b34694cddb4f81dd8b
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
